import { CatalogItem } from "@/interfaces/Catalog";

export const WHATSAPP_NUMBER = "584220183181";
const DEFAULT_WHATSAPP_TEXT =
  "Hola. Vengo de su página web y me gustaría consultar por este reloj.";

export const siteConfig = {
  brandName: "Relojes Venezuela",
  iconPath: "/icono.jpg",
  whatsappUrl: `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(
    DEFAULT_WHATSAPP_TEXT
  )}`,
  leadFormEndpoint: process.env.NEXT_PUBLIC_FORMSPREE_ENDPOINT ?? "",
};

export function buildWhatsAppUrl(message: string) {
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
}

export const catalogProductsCaballero: CatalogItem[] = [
  {
    id: "caballero-1",
    name: "Curren 8106",
    price: 24.99,
    originalPrice: 30,
    imageUrl: "/modelos/caballero/modelo1.jpg",
  },
  {
    id: "caballero-2",
    name: "Curren 8374",
    price: 29.99,
    originalPrice: 36,
    imageUrl: "/modelos/caballero/modelo2.jpg",
  },
  {
    id: "caballero-3",
    name: "Poedagar 825",
    price: 24.99,
    originalPrice: 30,
    imageUrl: "/modelos/caballero/modelo3.jpg",
  },
  {
    id: "caballero-4",
    name: "Curren 8457",
    price: 25.99,
    originalPrice: 32,
    imageUrl: "/modelos/caballero/modelo4.jpg",
  },
  {
    id: "caballero-5",
    name: "Curren 8458",
    price: 24.99,
    originalPrice: 31,
    imageUrl: "/modelos/caballero/modelo5.jpg",
  },
  {
    id: "caballero-6",
    name: "Onola 3826W",
    price: 26.75,
    originalPrice: 33,
    imageUrl: "/modelos/caballero/modelo6.jpg",
  },
  {
    id: "caballero-7",
    name: "Onola 3827D",
    price: 29.99,
    originalPrice: 39,
    imageUrl: "/modelos/caballero/modelo7.jpg",
  },
  {
    id: "caballero-8",
    name: "Curren 8427",
    price: 29.99,
    originalPrice: 40,
    imageUrl: "/modelos/caballero/modelo8.jpg",
  },
  {
    id: "caballero-9",
    name: "Curren 8401",
    price: 34.99,
    originalPrice: 45,
    imageUrl: "/modelos/caballero/modelo9.jpg",
  },
  {
    id: "caballero-10",
    name: "Curren 8459",
    price: 33.99,
    originalPrice: 43,
    imageUrl: "/modelos/caballero/modelo10.jpg",
  },
  {
    id: "caballero-11",
    name: "Wlisth 6147",
    price: 19.99,
    originalPrice: 28,
    imageUrl: "/modelos/caballero/modelo11.jpg",
  },
  {
    id: "caballero-12",
    name: "Megir 8601",
    price: 34.99,
    originalPrice: 47,
    imageUrl: "/modelos/caballero/modelo12.jpg",
  },
  {
    id: "caballero-13",
    name: "Curren 8443",
    price: 34.99,
    originalPrice: 45,
    imageUrl: "/modelos/caballero/modelo13.jpg",
  },
  {
    id: "caballero-14",
    name: "Curren 8476",
    price: 27.99,
    originalPrice: 35,
    imageUrl: "/modelos/caballero/modelo14.jpg",
  },
  {
    id: "caballero-15",
    name: "Curren 8411",
    price: 27.99,
    originalPrice: 35,
    imageUrl: "/modelos/caballero/modelo15.jpg",
  },
  {
    id: "caballero-16",
    name: "Curren 8442",
    price: 33.99,
    originalPrice: 44,
    imageUrl: "/modelos/caballero/modelo16.jpg",
  },
  {
    id: "caballero-17",
    name: "Poedagar 827",
    price: 22.40,
    originalPrice: 30,
    imageUrl: "/modelos/caballero/modelo17.jpg",
  },
  {
    id: "caballero-18",
    name: "Curren 8437",
    price: 29.99,
    originalPrice: 37,
    imageUrl: "/modelos/caballero/modelo18.jpg",
  },
  {
    id: "caballero-19",
    name: "Onola 3827W",
    price: 26.74,
    originalPrice: 33,
    imageUrl: "/modelos/caballero/modelo19.jpg",
  },
  {
    id: "caballero-20",
    name: "Curren 8438",
    price: 31.99,
    originalPrice: 37,
    imageUrl: "/modelos/caballero/modelo20.jpg",
  },
  {
    id: "caballero-21",
    name: "Curren 8471",
    price: 28.99,
    originalPrice: 34,
    imageUrl: "/modelos/caballero/modelo21.jpg",
  },
  {
    id: "caballero-22",
    name: "Curren 8473",
    price: 23.99,
    originalPrice: 30,
    imageUrl: "/modelos/caballero/modelo22.jpg",
  },
  {
    id: "caballero-23",
    name: "Curren 8406",
    price: 26.99,
    originalPrice: 34,
    imageUrl: "/modelos/caballero/modelo23.jpg",
  },
  {
    id: "caballero-24",
    name: "Curren 8435",
    price: 32.99,
    originalPrice: 40,
    imageUrl: "/modelos/caballero/modelo24.jpg",
  },
  {
    id: "caballero-25",
    name: "Curren 8452",
    price: 23.99,
    originalPrice: 29,
    imageUrl: "/modelos/caballero/modelo25.jpg",
  },
  {
    id: "caballero-26",
    name: "Curren 8375",
    price: 26.99,
    originalPrice: 35,
    imageUrl: "/modelos/caballero/modelo26.jpg",
  },
  {
    id: "caballero-27",
    name: "Curren 8365",
    price: 25.99,
    originalPrice: 32,
    imageUrl: "/modelos/caballero/modelo27.jpg",
  },
  {
    id: "caballero-28",
    name: "Curren 8472",
    price: 25.99,
    originalPrice: 32,
    imageUrl: "/modelos/caballero/modelo28.jpg",
  },
];

export const catalogProductsDamas: CatalogItem[] = [
  {
    id: "dama-1",
    name: "Curren 9095",
    price: 19.99,
    originalPrice: 27,
    imageUrl: "/modelos/dama/dama1.jpg",
  },
  {
    id: "dama-2",
    name: "Curren 9101",
    price: 24.99,
    originalPrice: 29,
    imageUrl: "/modelos/dama/dama2.jpg",
  },
  {
    id: "dama-3",
    name: "Curren 9109",
    price: 22.99,
    originalPrice: 28,
    imageUrl: "/modelos/dama/dama3.jpg",
  },
  {
    id: "dama-4",
    name: "Curren 9104",
    price: 19.99,
    originalPrice: 26,
    imageUrl: "/modelos/dama/dama4.jpg",
  },
  {
    id: "dama-5",
    name: "Curren 9088",
    price: 20.99,
    originalPrice: 27,
    imageUrl: "/modelos/dama/dama5.jpg",
  },
  {
    id: "dama-6",
    name: "Curren 9111",
    price: 23.99,
    originalPrice: 29,
    imageUrl: "/modelos/dama/dama6.jpg",
  },
  {
    id: "dama-7",
    name: "Curren 9096",
    price: 24.99,
    originalPrice: 29,
    imageUrl: "/modelos/dama/dama7.jpg",
  },
  {
    id: "dama-8",
    name: "Curren 9090",
    price: 19.99,
    originalPrice: 26,
    imageUrl: "/modelos/dama/dama8.jpg",
  },
  {
    id: "dama-9",
    name: "Curren 9099",
    price: 21.99,
    originalPrice: 28,
    imageUrl: "/modelos/dama/dama9.jpg",
  },
  {
    id: "dama-10",
    name: "Curren 8439",
    price: 24.99,
    originalPrice: 29,
    imageUrl: "/modelos/dama/dama10.jpg",
  },
  {
    id: "dama-11",
    name: "Poedagar 708",
    price: 23.45,
    originalPrice: 29,
    imageUrl: "/modelos/dama/dama11.jpg",
  },
  {
    id: "dama-12",
    name: "Curren 9094",
    price: 19.99,
    originalPrice: 26,
    imageUrl: "/modelos/dama/dama12.jpg",
  },
  {
    id: "dama-13",
    name: "Curren 9072",
    price: 24.99,
    originalPrice: 30,
    imageUrl: "/modelos/dama/dama13.jpg",
  },
  {
    id: "dama-14",
    name: "Curren 9106",
    price: 19.99,
    originalPrice: 27,
    imageUrl: "/modelos/dama/dama14.jpg",
  },
  {
    id: "dama-15",
    name: "Curren 9103",
    price: 22.75,
    originalPrice: 29,
    imageUrl: "/modelos/dama/dama15.jpg",
  },
  {
    id: "dama-16",
    name: "Curren 9068",
    price: 20.99,
    originalPrice: 27,
    imageUrl: "/modelos/dama/dama16.jpg",
  },
  {
    id: "dama-17",
    name: "Curren 9100",
    price: 24.99,
    originalPrice: 30,
    imageUrl: "/modelos/dama/dama17.jpg",
  },
];
